### ISSUE TITLE
Warnings with 2.7

### ISSUE THREAD

**Issue by ukd1** [basecamp/marginalia#103]
```
/Users/russ/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/marginalia-48a04a14b413/lib/marginalia.rb:94: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

**Comment by nickcampbell18** [comment]
There's a PR here to fix this: https://github.com/basecamp/marginalia/pull/101

**Comment by imajes** [comment]
@jeremy, @arthurnn: any chance this can get merged and a gem pushed? it's a tiny fix but is a genuine quality of life improvement :) thanks.

**Comment by arthurnn** [comment]
https://github.com/basecamp/marginalia/pull/101 was merged.. will release new version soon, thanks
