### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by joehorsnell** [basecamp/marginalia#108]
Hi,

Just opening an issue to request the status of this project - is it still active and maintained?

The last RubyGems version, [1.8.0](https://rubygems.org/gems/marginalia/versions/1.8.0), was released in March 2019 and there are a fair number of PRs open, some for nearly 18 months. Also the CI builds are currently broken and have been for some time, although #105 seems to fix that.

Many thanks.

**Comment by adityashedge** [comment]
@noahhl @qrush @arthurnn  Please comment!

**Comment by arthurnn** [comment]
Hi @joehorsnell @adityashedge . Yes this project is still maintained, and the latest version is used in production by GitHub dotcom main app. 
I just don't have a lot of time lately to review PRs, but I will do it in the near future. 
Thanks

**Comment by joehorsnell** [comment]
Thanks for the response @adityashedge and @arthurnn 👍.
