### ISSUE TITLE
New release for Ruby 2.7 fixes

### ISSUE THREAD

**Issue by JoeSouthan** [basecamp/marginalia#114]
Hi there!

Would you be able to cut a new release that includes the changes in #110 please?

Many thanks

**Comment by CamilleDrapier** [comment]
@arthurnn Sorry for asking this, but do you think you could make progress on this please? It would allow us to trim down huge number of these warnings in some of our projects without having to use the master branch directly in our gemfiles 🙏 🙇

**Comment by kbarrette** [comment]
@arthurnn any chance of a gem release? I see a few other things have hit master since #110 was merged as well. I'd love to be able to finish cleaning up my kwargs warnings now that Ruby 3 is released.

**Comment by arthurnn** [comment]
Happy new year. 

1.10.0 is out https://rubygems.org/gems/marginalia/versions/1.10.0

**Comment by kbarrette** [comment]
Thank you!
