### ISSUE TITLE
How to disable in test env?

### ISSUE THREAD

**Issue by guillaumebriday** [basecamp/marginalia#116]
I would like to disable this gem in test env. Is it possible?

Thanks!

**Comment by bheemreddy181** [comment]
you can group the gem like in gemfile 

```
group :development, :production do
  gem 'yahoo-weather'
end
```

**Comment by sj26** [comment]
You could configure marginalia to have no components in your tests environment. With no components, marginalia will not modify sql statements.

For example:

```
# config/environments/test.rb

# ...

Marginalia::Comment.components = []
```

or similar in your test or rspec helper, etc.

Or you could exclude it from your Gemfile using groups as above.
