### ISSUE TITLE
Question : Is it good idea to enable SQL logs in production?

### ISSUE THREAD

**Issue by bheemreddy181** [basecamp/marginalia#123]
I always get pushback from my teammates saying that we shouldn't enable debug logs for applications that will write SQL logs to the log file which will slow down the performance of your app

**Comment by sj26** [comment]
That's a big "It Depends"! You'd need to weight the value of those logs against the performance impact of generating and persisting the logs and the cost of storing and querying the logs. Not a question this gem can answer for you, though.
