### ISSUE TITLE
Trouble fetching current_admin

### ISSUE THREAD

**Issue by tysliu** [basecamp/marginalia#31]
I'm able to get controller.current admin from the view.
however when i did this in comment.rb
      def self.current_admin
        @controller.current_admin.to_s if @controller.respond_to? :current_admin
      end

 SystemStackError in ApplicationController#sitemap

stack level too deep

Application Trace | Framework Trace | Full Trace

actionpack (3.2.15) lib/action_dispatch/middleware/reloader.rb:70

Request

Parameters:

None

Show session dump

Show env dump
Response

Headers:

None

**Comment by sj26** [comment]
I'm going to close this issue as stale. But if you are still having this problem please re-open with a "full trace".
