### ISSUE TITLE
Initializes db connection during `rake assets:precompile` in rails 4

### ISSUE THREAD

**Issue by bcherry** [basecamp/marginalia#36]
It looks like this gem will cause an initialization of the database connection during it's require phase, which makes `rake assets:precompile` fail when run on a host without a database configuration. Rails 4 removed the `intialize_on_precompile` configuration, so it's important that this gem not trigger connection during initialization. For now, we can work around with environment variables but it would be good to get this fixed!

**Comment by eugeneius** [comment]
This was fixed by #42, which was released in v1.2.0.

**Comment by arthurnn** [comment]
thanks @eugeneius for noting that.. Will close the issue, please let me know if it is still a problem.
