### ISSUE TITLE
Namespace of controller is not included

### ISSUE THREAD

**Issue by klausmeyer** [basecamp/marginalia#40]
Hi,

we're using your gem since a few months in all our apps and are quite happy with it. It really makes the debugging for slow queries much more comfortable.

There is one topic that we'd like to improve and I'd like to hear your opinion about it. Currently the controller name included in the comment is missing the namespace which is sometimes very confusing.

E.g. since we're having an `AccountsController` and an `API::V1::AccountsController` in our application for both controllers the comment would look like the following one:

``` sql
SELECT * FROM accounts ... /* application:appname, controller: accounts, action: show */
```

The reason for this is the usage of the `ActionController::Base#controller_name` method.
What about changing it to using the class name? Or should we better add a second method like `self.controller_with_namespace` to the `Marginalia::Comment` module? Should I provide a pull request and would you probably merge it?

Cheers, Klaus

**Comment by ankane** [comment]
Not that we need another controller option, but `@controller.controller_path` may be a good candidate in a future major version.
