### ISSUE TITLE
Release a new version on rubygems.org to support Rails 5 Fix.

### ISSUE THREAD

**Issue by kwent** [basecamp/marginalia#58]
Hi,

Since `Rails 5.0.0` is officially out and final, it would be nice to release a new version on [rubygems.org](https://rubygems.org/)

The fix concerned is this one: https://github.com/basecamp/marginalia/commit/89d1a1ea8581f4794d894ae5219def819445c180

Regards

**Comment by arthurnn** [comment]
i will @kwent soon.

**Comment by BenFenner** [comment]
I too am making use of this gem and have upgraded to Rails 5.
I'm seeing deprecation warnings for the `around_filter` calls that should be `around_action` calls.
That might also need to be worked before this release is finalized.
I could try to setup a pull request for that if you'd like.
Cheers!

**Comment by kwent** [comment]
@arthurnn Any news about releasing a version on rubygems.org ?

Regards,

**Comment by arthurnn** [comment]
new version released https://rubygems.org/gems/marginalia/versions/1.4.0

**Comment by BenFenner** [comment]
Excellent work. Thank you!
