### ISSUE TITLE
Rails 5 / Ruby 2.5 bug

### ISSUE THREAD

**Issue by shaneog** [basecamp/marginalia#70]
I receive the calling line of `usr/local/lib/ruby/2.5.0/monitor.rb:226:in 'mon_synchronize'` using Rails 5 and Ruby 2.5, which is not useful.

I've added a [PR](https://github.com/basecamp/marginalia/pull/69)to add Ruby 2.5 support to the test suite, to see if there are breaking tests.

**Versions:**
Rails: 5.1.6
Ruby: 2.5.1
Marginalia: 1.5.0

OT: is this project maintained any more?

**Comment by oyeanuj** [comment]
@shaneog Have you gotten it to work with Rails 5.2 and Ruby 2.5.1?

cc: @arthurnn Should one expect this to work with the latest versions of Rails & Ruby?

**Comment by shaneog** [comment]
I'm still seeing this on Ruby 2.5

**Comment by fidalgo** [comment]
With Ruby 2.5.1, Rails 5.2.0 and marginalia 1.5.0 I don't see this bug. Also I'm not using any customization on marginalia.

**Comment by phallstrom** [comment]
Ruby 2.5.5, Rails 5.1.7, marginalia 1.8.0, seeing this bug.

**Comment by phallstrom** [comment]
You can work around this by defining your own lines to ignore.

```
# See https://github.com/basecamp/marginalia/blob/master/lib/marginalia/comment.rb#L109
# Our addition excludes:  "/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'"
Marginalia::Comment.lines_to_ignore = /\.rvm|gem|vendor\/|marginalia|rbenv|\/monitor.rb.*mon_synchronize/
```
