### ISSUE TITLE
Odd behaviour if code contains syntax errors or produces a stack level too low error

### ISSUE THREAD

**Issue by NielsKSchjoedt** [basecamp/marginalia#71]
Marginalia is obfuscating the root cause of syntax errors and recursive code etc. An example:

```ruby
class Test
  incude SomeModule
end
```

When executing the above code, instead of getting a `undefined method incude` I will get a recursive death spiral outputting:

`./vendor/bundle/ruby/2.4.0/gems/marginalia-1.5.0/lib/marginalia.rb:58:in 'execute_with_marginalia'`

This is really nasty, as e.g. your test suite will will produce an unusable output if a developer have made a syntax error or similar, instead of failing the specs with a useful one.

**Comment by sj26** [comment]
I'm going to close this issue, presuming it is stale. Please re-open if you're still having this issue.

But that's very odd! I'm not sure marginalia is the cause of this issue. Perhaps look at the ancestry of the module experiencing this issue and see if there's something odd going on.
