### ISSUE TITLE
Strategy for using outside Rails controllers like grape? 

### ISSUE THREAD

**Issue by rromanchuk** [basecamp/marginalia#75]
I love using this gem with `pghero`, but i'm wondering the best way to make use of customizing my my own component to use outside of a rails controller, in my case it's grape. 

I know i can add my own component, and in my case, grape offers `env["api.endpoint"]` https://github.com/ruby-grape/grape#current-route-and-endpoint but i'm not sure what the best way to pass this information in from what i believe requires a grape middlewear from `Grape::Middleware::Base`

You can go ahead and close this, just seeking advice, improving SEO for others. Or maybe there is a simpler solution as this has most likely aged.

**Comment by sj26** [comment]
You could probably do something similar to the actioncontroller instrumentation:

https://github.com/basecamp/marginalia/blob/b04051c8fb1a981f139763e1fc948c8265be4fb6/lib/marginalia.rb#L109-L126
https://github.com/basecamp/marginalia/blob/b04051c8fb1a981f139763e1fc948c8265be4fb6/lib/marginalia/comment.rb#L10-L12
https://github.com/basecamp/marginalia/blob/b04051c8fb1a981f139763e1fc948c8265be4fb6/lib/marginalia/comment.rb#L94-L104

Good luck!
