### ISSUE TITLE
mysql gem built even when not necessary

### ISSUE THREAD

**Issue by viraptor** [basecamp/marginalia#76]
If I include `marginalia` in a Gemfile, even if I don't use/need `mysql`, it looks like the gem will always be built on ruby < 2.4.
It seems like there's no differentiation between installing `marginalia` as a dependency and for development in case of that extension.

This is causing an issue, because I can't successfully build the `mysql` gem on the current system.

**Comment by arthurnn** [comment]
Good catch. that is not good
