### ISSUE TITLE
Sidekiq documents are now out-of-date

### ISSUE THREAD

**Issue by geoffharcourt** [basecamp/marginalia#87]
The gem now includes the Sidekiq middleware, so the example in the wiki might lead someone to duplicate the code in their app, potentially overriding any future upstream improvements or fixes.

I tried forking the wiki, but it seems like it's not editable by non-committers.

**Comment by arthurnn** [comment]
@geoffharcourt thanks for noticing that. would you mind writing an update here, and I can copy/paste to the wiki?

thanks a lot for your help

**Comment by geoffharcourt** [comment]
```markdown

# Sidekiq Integration

Marginalia has built-in Sidekiq integration. If you were using custom middleware before, you can remove it and use the gem-provided instrumentation.

Enable the Sidekiq instrumentation:

```ruby
# In config/initializers/sidekiq.rb
Marginalia::SidekiqInstrumentation.enable!
```

Add the `sidekiq_job` component to your annotations:

```ruby
# In config/initializers/marginalia.rb
Marginalia::Comment.components = %i[
  controller_with_namespace
  action
  sidekiq_job
]
```

If you use `job` and `sidekiq_job` you may get some annotation sources overwritten as `Hash`.

**Comment by arthurnn** [comment]
Thanks. All updated.
