### ISSUE TITLE
Rails 6.0 Connection Adapter Problem

### ISSUE THREAD

**Issue by simonrentzke** [basecamp/marginalia#97]
```
 undefined method `spec' for #<ActiveRecord::ConnectionAdapters::NullPool:0x00007ffbee3e7eb0>
 from  marginalia/lib/marginalia/comment.rb:166:in `connection_config'
```

I'm unable to start the application on Rails 6 with Marginalia. 

I'm using:
- [Multiple Databases](https://guides.rubyonrails.org/active_record_multiple_databases.html)
- Ruby 2.5.7
- Rails 6.0.2.1
- Marginalia 1.8.0

Anyone else having this problem?

**Comment by simonrentzke** [comment]
Ah, looks like there is a PR already https://github.com/basecamp/marginalia/pull/91

**Comment by jeremy** [comment]
Following up in #91. Thanks @simonrentzke 🙇🏼‍♂️
